# Generated by Django 5.1.7 on 2025-03-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(default='album_covers/default.jpg', upload_to='album_covers/'),
        ),
    ]
